// Code generated by goro; DO NOT EDIT.

package myrepo

// This file was generated by the goro tool.
// Editing this file might prove futile when you re-run the goro commands

import (
	"database/sql"
	"testapp/internal/adapter/mysqlrepo"
)

type Repository struct {
	mysqlrepo.Transactor
}

func NewRepository(conn *sql.DB) *Repository {
	return &Repository{
		mysqlrepo.NewTransactor(conn),
	}
}
