// Code generated by goro; DO NOT EDIT.

package app

// This file was generated by the goro tool.
// Editing this file might prove futile when you re-run the goro commands

import (
	"testapp/pkg/logger"
)

func (a *App) initLogger() {

	l := logger.NewLogger()

	a.logger = l
}
