// Code generated by goro;

package productservice

// This file was generated by the goro tool.

type productApi interface {

	// TODO: define interface to inject a service or an adapter
}

type Service struct {
	productApi productApi
}

func NewService(productApi productApi) *Service {
	return &Service{

		productApi: productApi,
	}
}
