// Code generated by goro;

package bankapi

// This file was generated by the goro tool.

import (
	"net/http"
)

type Repository struct {
	Client *http.Client
}

func NewRepository(client *http.Client) *Repository {
	return &Repository{
		Client: client,
	}
}
