// Code generated by goro;

package ordersrepo

// This file was generated by the goro tool.

import (
	"net/http"
)

type Repository struct {
	client *http.Client
}

func NewRepository(client *http.Client) *Repository {
	return &Repository{

		client: client,
	}
}
