// Code generated by goro;

package pingpong

// This file was generated by the goro tool.

import (
	"testapp/internal/service"
)

type myRepo interface {
	service.Transactor

	// TODO: define interface to inject a service or an adapter
}

type ordersRepo interface {
	service.Transactor

	// TODO: define interface to inject a service or an adapter
}

type Service struct {
	myRepo myRepo

	ordersRepo ordersRepo
}

func NewService(myRepo myRepo, ordersRepo ordersRepo) *Service {
	return &Service{

		myRepo: myRepo,

		ordersRepo: ordersRepo,
	}
}
