// Code generated by goro;

package orderservice

// This file was generated by the goro tool.

type ordersRepo interface {
	// TODO: define interface to inject a service or an adapter
}

type Service struct {
	ordersRepo ordersRepo
}

func NewService(ordersRepo ordersRepo) *Service {
	return &Service{

		ordersRepo: ordersRepo,
	}
}
