// Code generated by goro; DO NOT EDIT.

package clientrepo

// This file was generated by the goro tool.
// Editing this file might prove futile when you re-run the goro commands

import (
	"github.com/jmoiron/sqlx"
	"testapp/internal/adapter/mysqlxrepo"
)

type Repository struct {
	mysqlxrepo.Transactor
}

func NewRepository(conn *sqlx.DB) *Repository {
	return &Repository{
		mysqlxrepo.NewTransactor(conn),
	}
}
