// Code generated by goro;

package clientservice

// This file was generated by the goro tool.

import (
	"testapp/internal/service"
)

type clientRepo interface {
	service.Transactor

	// TODO: define interface to inject a service or an adapter
}

type Service struct {
	clientRepo clientRepo
}

func NewService(clientRepo clientRepo) *Service {
	return &Service{

		clientRepo: clientRepo,
	}
}
