// Code generated by goro; DO NOT EDIT.

package usecase

// This file was generated by the goro tool.
// Editing this file might prove futile when you re-run the goro commands

type myService interface {
	// TODO: define interface to inject a service
}

type pingPong interface {
	// TODO: define interface to inject a service
}

type UseCase struct {
	myService myService
	pingPong  pingPong
}

func NewUseCase(myService myService, pingPong pingPong) *UseCase {
	return &UseCase{
		myService: myService,
		pingPong:  pingPong,
	}
}
