// Code generated by goro;

package usecase

// This file was generated by the goro tool.

type myService interface {
	// TODO: define interface to inject a service
}

type pingPong interface {
	// TODO: define interface to inject a service
}

type UseCase struct {
	myService myService
	pingPong  pingPong
}

func NewUseCase(myService myService, pingPong pingPong) *UseCase {
	return &UseCase{
		myService: myService,
		pingPong:  pingPong,
	}
}
