// Code generated by goro; DO NOT EDIT.

package usecase

// This file was generated by the goro tool.
// Editing this file might prove futile when you re-run the goro commands

type myService interface {
	// TODO: define interface to inject a service
}

type UseCase struct {
	myService myService
}

func NewUseCase(myService myService) *UseCase {
	return &UseCase{
		myService: myService,
	}
}
