// Code generated by goro;

package myservice

// This file was generated by the goro tool.

import (
	"testapp/internal/service"
)

type bankApi interface {

	// TODO: define interface to inject a service or an adapter
}

type myRepo interface {
	service.Transactor

	// TODO: define interface to inject a service or an adapter
}

type Service struct {
	bankApi bankApi

	myRepo myRepo
}

func NewService(bankApi bankApi, myRepo myRepo) *Service {
	return &Service{

		bankApi: bankApi,

		myRepo: myRepo,
	}
}
