// Code generated by goro;

package ordersrepo

// This file was generated by the goro tool.

import (
	"github.com/jmoiron/sqlx"

	"testapp/internal/adapter/pgsqlxrepo"
)

type Repository struct {
	pgsqlxrepo.Transactor
}

func NewRepository(conn *sqlx.DB) *Repository {
	return &Repository{
		pgsqlxrepo.NewTransactor(conn),
	}
}
